export const ALL_POST_REQUEST = "POST_REQUEST";
export const ALL_POST_SUCCESS = "POST_SUCCESS";
export const ALL_POST_FAIL = "POST_FAIL";


export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
